name: Compress MP4
on: workflow_dispatch

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download from Google Drive
        run: |
          pip install gdown
          gdown "1NvJNNl9_JaG5wx-kAaLD5-qfmQP3-ytt" -O "input.mp4"
      
      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg
      
      - name: Compress MP4
        run: |
          ffmpeg -i "input.mp4" \
            -c:v libx264 \
            -crf 28 \
            -preset slow \
            -c:a aac \
            -b:a 128k \
            "output.mp4"
      
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.mp4
